// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: blob/api/v1/blob.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blob struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Content     []byte                 `protobuf:"bytes,2,opt,name=content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_blob_api_v1_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_blob_api_v1_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Blob) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Blob) GetContent() []byte {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *Blob) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Blob) SetContent(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Content = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Blob) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Blob) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Blob) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Blob) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Content = nil
}

type Blob_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name    *string
	Content []byte
}

func (b0 Blob_builder) Build() *Blob {
	m0 := &Blob{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Content = b.Content
	}
	return m0
}

type ListBlobsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path        *string                `protobuf:"bytes,1,opt,name=path"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListBlobsRequest) Reset() {
	*x = ListBlobsRequest{}
	mi := &file_blob_api_v1_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobsRequest) ProtoMessage() {}

func (x *ListBlobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blob_api_v1_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListBlobsRequest) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *ListBlobsRequest) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ListBlobsRequest) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListBlobsRequest) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Path = nil
}

type ListBlobsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path *string
}

func (b0 ListBlobsRequest_builder) Build() *ListBlobsRequest {
	m0 := &ListBlobsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Path = b.Path
	}
	return m0
}

type ListBlobsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names []string               `protobuf:"bytes,1,rep,name=names"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListBlobsResponse) Reset() {
	*x = ListBlobsResponse{}
	mi := &file_blob_api_v1_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobsResponse) ProtoMessage() {}

func (x *ListBlobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blob_api_v1_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListBlobsResponse) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *ListBlobsResponse) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

type ListBlobsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Names []string
}

func (b0 ListBlobsResponse_builder) Build() *ListBlobsResponse {
	m0 := &ListBlobsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	return m0
}

type GetBlobRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBlobRequest) Reset() {
	*x = GetBlobRequest{}
	mi := &file_blob_api_v1_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRequest) ProtoMessage() {}

func (x *GetBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blob_api_v1_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBlobRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *GetBlobRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetBlobRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetBlobRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type GetBlobRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 GetBlobRequest_builder) Build() *GetBlobRequest {
	m0 := &GetBlobRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type GetBlobResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Blob *Blob                  `protobuf:"bytes,1,opt,name=blob"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBlobResponse) Reset() {
	*x = GetBlobResponse{}
	mi := &file_blob_api_v1_blob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobResponse) ProtoMessage() {}

func (x *GetBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blob_api_v1_blob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBlobResponse) GetBlob() *Blob {
	if x != nil {
		return x.xxx_hidden_Blob
	}
	return nil
}

func (x *GetBlobResponse) SetBlob(v *Blob) {
	x.xxx_hidden_Blob = v
}

func (x *GetBlobResponse) HasBlob() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Blob != nil
}

func (x *GetBlobResponse) ClearBlob() {
	x.xxx_hidden_Blob = nil
}

type GetBlobResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Blob *Blob
}

func (b0 GetBlobResponse_builder) Build() *GetBlobResponse {
	m0 := &GetBlobResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Blob = b.Blob
	return m0
}

type SetBlobRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Content     []byte                 `protobuf:"bytes,2,opt,name=content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetBlobRequest) Reset() {
	*x = SetBlobRequest{}
	mi := &file_blob_api_v1_blob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlobRequest) ProtoMessage() {}

func (x *SetBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blob_api_v1_blob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetBlobRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *SetBlobRequest) GetContent() []byte {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *SetBlobRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SetBlobRequest) SetContent(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Content = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SetBlobRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetBlobRequest) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SetBlobRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *SetBlobRequest) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Content = nil
}

type SetBlobRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name    *string
	Content []byte
}

func (b0 SetBlobRequest_builder) Build() *SetBlobRequest {
	m0 := &SetBlobRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Content = b.Content
	}
	return m0
}

type SetBlobResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBlobResponse) Reset() {
	*x = SetBlobResponse{}
	mi := &file_blob_api_v1_blob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlobResponse) ProtoMessage() {}

func (x *SetBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blob_api_v1_blob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetBlobResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetBlobResponse_builder) Build() *SetBlobResponse {
	m0 := &SetBlobResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DeleteBlobRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteBlobRequest) Reset() {
	*x = DeleteBlobRequest{}
	mi := &file_blob_api_v1_blob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobRequest) ProtoMessage() {}

func (x *DeleteBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blob_api_v1_blob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteBlobRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *DeleteBlobRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteBlobRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteBlobRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type DeleteBlobRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 DeleteBlobRequest_builder) Build() *DeleteBlobRequest {
	m0 := &DeleteBlobRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type DeleteBlobResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlobResponse) Reset() {
	*x = DeleteBlobResponse{}
	mi := &file_blob_api_v1_blob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobResponse) ProtoMessage() {}

func (x *DeleteBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blob_api_v1_blob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteBlobResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteBlobResponse_builder) Build() *DeleteBlobResponse {
	m0 := &DeleteBlobResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_blob_api_v1_blob_proto protoreflect.FileDescriptor

const file_blob_api_v1_blob_proto_rawDesc = "" +
	"\n" +
	"\x16blob/api/v1/blob.proto\x12\vblob.api.v1\x1a\x1bbuf/validate/validate.proto\x1a!google/protobuf/go_features.proto\"D\n" +
	"\x04Blob\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\acontent\x18\x02 \x01(\fB\x06\xbaH\x03\xc8\x01\x01R\acontent\".\n" +
	"\x10ListBlobsRequest\x12\x1a\n" +
	"\x04path\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04path\")\n" +
	"\x11ListBlobsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\",\n" +
	"\x0eGetBlobRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"@\n" +
	"\x0fGetBlobResponse\x12-\n" +
	"\x04blob\x18\x01 \x01(\v2\x11.blob.api.v1.BlobB\x06\xbaH\x03\xc8\x01\x01R\x04blob\"N\n" +
	"\x0eSetBlobRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\acontent\x18\x02 \x01(\fB\x06\xbaH\x03\xc8\x01\x01R\acontent\"\x11\n" +
	"\x0fSetBlobResponse\"/\n" +
	"\x11DeleteBlobRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"\x14\n" +
	"\x12DeleteBlobResponse2\xc8\x02\n" +
	"\vBlobService\x12O\n" +
	"\tListBlobs\x12\x1d.blob.api.v1.ListBlobsRequest\x1a\x1e.blob.api.v1.ListBlobsResponse\"\x03\x90\x02\x01\x12I\n" +
	"\aGetBlob\x12\x1b.blob.api.v1.GetBlobRequest\x1a\x1c.blob.api.v1.GetBlobResponse\"\x03\x90\x02\x01\x12I\n" +
	"\aSetBlob\x12\x1b.blob.api.v1.SetBlobRequest\x1a\x1c.blob.api.v1.SetBlobResponse\"\x03\x90\x02\x02\x12R\n" +
	"\n" +
	"DeleteBlob\x12\x1e.blob.api.v1.DeleteBlobRequest\x1a\x1f.blob.api.v1.DeleteBlobResponse\"\x03\x90\x02\x00B\xa5\x01\n" +
	"\x0fcom.blob.api.v1B\tBlobProtoP\x01Z1github.com/cmgsj/blob/pkg/proto/blob/api/v1;apiv1\xa2\x02\x03BAX\xaa\x02\vBlob.Api.V1\xca\x02\vBlob\\Api\\V1\xe2\x02\x17Blob\\Api\\V1\\GPBMetadata\xea\x02\rBlob::Api::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_blob_api_v1_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_blob_api_v1_blob_proto_goTypes = []any{
	(*Blob)(nil),               // 0: blob.api.v1.Blob
	(*ListBlobsRequest)(nil),   // 1: blob.api.v1.ListBlobsRequest
	(*ListBlobsResponse)(nil),  // 2: blob.api.v1.ListBlobsResponse
	(*GetBlobRequest)(nil),     // 3: blob.api.v1.GetBlobRequest
	(*GetBlobResponse)(nil),    // 4: blob.api.v1.GetBlobResponse
	(*SetBlobRequest)(nil),     // 5: blob.api.v1.SetBlobRequest
	(*SetBlobResponse)(nil),    // 6: blob.api.v1.SetBlobResponse
	(*DeleteBlobRequest)(nil),  // 7: blob.api.v1.DeleteBlobRequest
	(*DeleteBlobResponse)(nil), // 8: blob.api.v1.DeleteBlobResponse
}
var file_blob_api_v1_blob_proto_depIdxs = []int32{
	0, // 0: blob.api.v1.GetBlobResponse.blob:type_name -> blob.api.v1.Blob
	1, // 1: blob.api.v1.BlobService.ListBlobs:input_type -> blob.api.v1.ListBlobsRequest
	3, // 2: blob.api.v1.BlobService.GetBlob:input_type -> blob.api.v1.GetBlobRequest
	5, // 3: blob.api.v1.BlobService.SetBlob:input_type -> blob.api.v1.SetBlobRequest
	7, // 4: blob.api.v1.BlobService.DeleteBlob:input_type -> blob.api.v1.DeleteBlobRequest
	2, // 5: blob.api.v1.BlobService.ListBlobs:output_type -> blob.api.v1.ListBlobsResponse
	4, // 6: blob.api.v1.BlobService.GetBlob:output_type -> blob.api.v1.GetBlobResponse
	6, // 7: blob.api.v1.BlobService.SetBlob:output_type -> blob.api.v1.SetBlobResponse
	8, // 8: blob.api.v1.BlobService.DeleteBlob:output_type -> blob.api.v1.DeleteBlobResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blob_api_v1_blob_proto_init() }
func file_blob_api_v1_blob_proto_init() {
	if File_blob_api_v1_blob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blob_api_v1_blob_proto_rawDesc), len(file_blob_api_v1_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blob_api_v1_blob_proto_goTypes,
		DependencyIndexes: file_blob_api_v1_blob_proto_depIdxs,
		MessageInfos:      file_blob_api_v1_blob_proto_msgTypes,
	}.Build()
	File_blob_api_v1_blob_proto = out.File
	file_blob_api_v1_blob_proto_goTypes = nil
	file_blob_api_v1_blob_proto_depIdxs = nil
}
