services:
  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address=:9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password

  minio_init:
    container_name: minio_init
    image: minio/mc
    depends_on:
      - minio
    entrypoint: |
      /bin/bash -c "sleep 5 && mc config host add local http://minio:9000 root password && (mc rm -r --force local/test; mc mb local/test)"
