services:
  gcs:
    container_name: gcs
    image: fsouza/fake-gcs-server
    command: --scheme=http
    ports:
      - 4443:4443
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/gcs:/data

  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address=:9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password

  minio_init:
    container_name: minio_init
    image: minio/mc
    depends_on:
      - minio
    entrypoint: |
      /bin/bash -c "sleep 5 && mc config host add local http://minio:9000 root password && (mc rm -r --force local/cmgsj; mc mb local/cmgsj)"

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
