// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: blob/api/v1/blob.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cmgsj/blob/pkg/proto/blob/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BlobServiceName is the fully-qualified name of the BlobService service.
	BlobServiceName = "blob.api.v1.BlobService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BlobServiceListBlobsProcedure is the fully-qualified name of the BlobService's ListBlobs RPC.
	BlobServiceListBlobsProcedure = "/blob.api.v1.BlobService/ListBlobs"
	// BlobServiceGetBlobProcedure is the fully-qualified name of the BlobService's GetBlob RPC.
	BlobServiceGetBlobProcedure = "/blob.api.v1.BlobService/GetBlob"
	// BlobServiceSetBlobProcedure is the fully-qualified name of the BlobService's SetBlob RPC.
	BlobServiceSetBlobProcedure = "/blob.api.v1.BlobService/SetBlob"
	// BlobServiceDeleteBlobProcedure is the fully-qualified name of the BlobService's DeleteBlob RPC.
	BlobServiceDeleteBlobProcedure = "/blob.api.v1.BlobService/DeleteBlob"
)

// BlobServiceClient is a client for the blob.api.v1.BlobService service.
type BlobServiceClient interface {
	ListBlobs(context.Context, *connect.Request[v1.ListBlobsRequest]) (*connect.Response[v1.ListBlobsResponse], error)
	GetBlob(context.Context, *connect.Request[v1.GetBlobRequest]) (*connect.Response[v1.GetBlobResponse], error)
	SetBlob(context.Context, *connect.Request[v1.SetBlobRequest]) (*connect.Response[v1.SetBlobResponse], error)
	DeleteBlob(context.Context, *connect.Request[v1.DeleteBlobRequest]) (*connect.Response[v1.DeleteBlobResponse], error)
}

// NewBlobServiceClient constructs a client for the blob.api.v1.BlobService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBlobServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BlobServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	blobServiceMethods := v1.File_blob_api_v1_blob_proto.Services().ByName("BlobService").Methods()
	return &blobServiceClient{
		listBlobs: connect.NewClient[v1.ListBlobsRequest, v1.ListBlobsResponse](
			httpClient,
			baseURL+BlobServiceListBlobsProcedure,
			connect.WithSchema(blobServiceMethods.ByName("ListBlobs")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getBlob: connect.NewClient[v1.GetBlobRequest, v1.GetBlobResponse](
			httpClient,
			baseURL+BlobServiceGetBlobProcedure,
			connect.WithSchema(blobServiceMethods.ByName("GetBlob")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		setBlob: connect.NewClient[v1.SetBlobRequest, v1.SetBlobResponse](
			httpClient,
			baseURL+BlobServiceSetBlobProcedure,
			connect.WithSchema(blobServiceMethods.ByName("SetBlob")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		deleteBlob: connect.NewClient[v1.DeleteBlobRequest, v1.DeleteBlobResponse](
			httpClient,
			baseURL+BlobServiceDeleteBlobProcedure,
			connect.WithSchema(blobServiceMethods.ByName("DeleteBlob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// blobServiceClient implements BlobServiceClient.
type blobServiceClient struct {
	listBlobs  *connect.Client[v1.ListBlobsRequest, v1.ListBlobsResponse]
	getBlob    *connect.Client[v1.GetBlobRequest, v1.GetBlobResponse]
	setBlob    *connect.Client[v1.SetBlobRequest, v1.SetBlobResponse]
	deleteBlob *connect.Client[v1.DeleteBlobRequest, v1.DeleteBlobResponse]
}

// ListBlobs calls blob.api.v1.BlobService.ListBlobs.
func (c *blobServiceClient) ListBlobs(ctx context.Context, req *connect.Request[v1.ListBlobsRequest]) (*connect.Response[v1.ListBlobsResponse], error) {
	return c.listBlobs.CallUnary(ctx, req)
}

// GetBlob calls blob.api.v1.BlobService.GetBlob.
func (c *blobServiceClient) GetBlob(ctx context.Context, req *connect.Request[v1.GetBlobRequest]) (*connect.Response[v1.GetBlobResponse], error) {
	return c.getBlob.CallUnary(ctx, req)
}

// SetBlob calls blob.api.v1.BlobService.SetBlob.
func (c *blobServiceClient) SetBlob(ctx context.Context, req *connect.Request[v1.SetBlobRequest]) (*connect.Response[v1.SetBlobResponse], error) {
	return c.setBlob.CallUnary(ctx, req)
}

// DeleteBlob calls blob.api.v1.BlobService.DeleteBlob.
func (c *blobServiceClient) DeleteBlob(ctx context.Context, req *connect.Request[v1.DeleteBlobRequest]) (*connect.Response[v1.DeleteBlobResponse], error) {
	return c.deleteBlob.CallUnary(ctx, req)
}

// BlobServiceHandler is an implementation of the blob.api.v1.BlobService service.
type BlobServiceHandler interface {
	ListBlobs(context.Context, *connect.Request[v1.ListBlobsRequest]) (*connect.Response[v1.ListBlobsResponse], error)
	GetBlob(context.Context, *connect.Request[v1.GetBlobRequest]) (*connect.Response[v1.GetBlobResponse], error)
	SetBlob(context.Context, *connect.Request[v1.SetBlobRequest]) (*connect.Response[v1.SetBlobResponse], error)
	DeleteBlob(context.Context, *connect.Request[v1.DeleteBlobRequest]) (*connect.Response[v1.DeleteBlobResponse], error)
}

// NewBlobServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBlobServiceHandler(svc BlobServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	blobServiceMethods := v1.File_blob_api_v1_blob_proto.Services().ByName("BlobService").Methods()
	blobServiceListBlobsHandler := connect.NewUnaryHandler(
		BlobServiceListBlobsProcedure,
		svc.ListBlobs,
		connect.WithSchema(blobServiceMethods.ByName("ListBlobs")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	blobServiceGetBlobHandler := connect.NewUnaryHandler(
		BlobServiceGetBlobProcedure,
		svc.GetBlob,
		connect.WithSchema(blobServiceMethods.ByName("GetBlob")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	blobServiceSetBlobHandler := connect.NewUnaryHandler(
		BlobServiceSetBlobProcedure,
		svc.SetBlob,
		connect.WithSchema(blobServiceMethods.ByName("SetBlob")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	blobServiceDeleteBlobHandler := connect.NewUnaryHandler(
		BlobServiceDeleteBlobProcedure,
		svc.DeleteBlob,
		connect.WithSchema(blobServiceMethods.ByName("DeleteBlob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/blob.api.v1.BlobService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BlobServiceListBlobsProcedure:
			blobServiceListBlobsHandler.ServeHTTP(w, r)
		case BlobServiceGetBlobProcedure:
			blobServiceGetBlobHandler.ServeHTTP(w, r)
		case BlobServiceSetBlobProcedure:
			blobServiceSetBlobHandler.ServeHTTP(w, r)
		case BlobServiceDeleteBlobProcedure:
			blobServiceDeleteBlobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBlobServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBlobServiceHandler struct{}

func (UnimplementedBlobServiceHandler) ListBlobs(context.Context, *connect.Request[v1.ListBlobsRequest]) (*connect.Response[v1.ListBlobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blob.api.v1.BlobService.ListBlobs is not implemented"))
}

func (UnimplementedBlobServiceHandler) GetBlob(context.Context, *connect.Request[v1.GetBlobRequest]) (*connect.Response[v1.GetBlobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blob.api.v1.BlobService.GetBlob is not implemented"))
}

func (UnimplementedBlobServiceHandler) SetBlob(context.Context, *connect.Request[v1.SetBlobRequest]) (*connect.Response[v1.SetBlobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blob.api.v1.BlobService.SetBlob is not implemented"))
}

func (UnimplementedBlobServiceHandler) DeleteBlob(context.Context, *connect.Request[v1.DeleteBlobRequest]) (*connect.Response[v1.DeleteBlobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("blob.api.v1.BlobService.DeleteBlob is not implemented"))
}
